### ISSUE TITLE
Could you provide all CAMs from SEAM ?

### ISSUE THREAD

**Issue by pigcv** [twke18/SPML#4]
https://github.com/twke18/SPML/blob/1bacae8963176489cda465e8e9b1f5b7384ace57/bashscripts/voc12/train_spml_tag.sh#L219

As can be seen in Line 219 of 'train_spml_tag.sh', the method need train+aug CAMs, but this repo doesn't seem to provide it. Could you upload it?

**Comment by twke18** [comment]
Since the total file size is really huge (~16GB), we suggest to follow the [SEAM](https://github.com/YudeWang/SEAM) repo's instruction to generate train+aug CAMs.

**Comment by pigcv** [comment]
> Since the total file size is really huge (~16GB), we suggest to follow the [SEAM](https://github.com/YudeWang/SEAM) repo's instruction to generate train+aug CAMs.

Thanks for your replay.

**Comment by pigcv** [comment]
> Since the total file size is really huge (~16GB), we suggest to follow the [SEAM](https://github.com/YudeWang/SEAM) repo's instruction to generate train+aug CAMs.

Thanks for your reply.
